namespace BloogBot.AI.StateMachine;

/// <summary>
/// Transition triggers consumed by <see cref="BotActivityStateMachine"/>.
/// </summary>
public enum Trigger
{
    HealthRestored,
    QuestComplete,
    QuestFailed,
    ProfessionLevelUp,
    TalentPointsAttributed,
    EquipmentChanged,
    TradeComplete,
    GuildingEnded,
    ChattingEnded,
    HelpingEnded,
    MailingEnded,
    PartyEnded,
    RolePlayEnded,
    CombatEnded,
    BattlegroundEnded,
    DungeonEnded,
    RaidEnded,
    PvPEnded,
    CampingEnded,
    AuctionEnded,
    BankingEnded,
    VendingEnded,
    ExploringEnded,
    TravelEnded,
    EscapeSucceeded,
    EscapeFailed,
    PartyInvite,
    GuildInvite,
    LowHealth,
    TalentPointsAvailable,
    TradeRequested,
    ChatMessageReceived,
    HelpRequested,
    MailReceived,
    RolePlayEngaged,
    CombatStarted,
    BattlegroundStarted,
    DungeonStarted,
    RaidStarted,
    PvPEngaged,
    CampingStarted,
    AuctionStarted,
    BankingNeeded,
    VendorNeeded,
    ExplorationStarted,
    TravelRequired,
    EscapeRequired,
    EventStarted,
    EventEnded
}
