name: wwow

services:
  realmd:
    image: ghcr.io/mserajnik/vmangos-server:5875
    container_name: realmd
    restart: unless-stopped
    command: ["/bin/sh", "/wwow-docker/start-realmd.sh"]
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3724"]
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 2m
    environment:
      WWOW_VMANGOS_DB_HOST: ${WWOW_VMANGOS_DB_HOST:-maria-db}
      WWOW_VMANGOS_DB_PORT: ${WWOW_VMANGOS_DB_PORT:-3306}
      WWOW_VMANGOS_DB_USER: ${WWOW_VMANGOS_DB_ROOT_USER:-root}
      WWOW_VMANGOS_DB_PASSWORD: ${WWOW_VMANGOS_DB_ROOT_PASSWORD:-root}
      WWOW_VMANGOS_REALMD_PORT: ${WWOW_VMANGOS_REALMD_PORT:-3724}
    networks:
      - gameserver-net
    ports:
      - "${WWOW_VMANGOS_REALMD_PUBLISHED_PORT:-3724}:3724"
    volumes:
      - ${WWOW_VMANGOS_SERVER_CONFIG_DIR:-D:/vmangos-server}/realmd.conf:/wwow-input/realmd.conf:ro
      - ./docker/linux/vmangos:/wwow-docker:ro
      - ./docker/linux/vmangos/storage/realmd/logs:/opt/vmangos/storage/logs

  mangosd:
    image: ghcr.io/mserajnik/vmangos-server:5875
    container_name: mangosd
    restart: unless-stopped
    command: ["/bin/sh", "/wwow-docker/start-mangosd.sh"]
    depends_on:
      realmd:
        condition: service_started
    tty: true
    stdin_open: true
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8085"]
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 10m
    environment:
      WWOW_VMANGOS_DB_HOST: ${WWOW_VMANGOS_DB_HOST:-maria-db}
      WWOW_VMANGOS_DB_PORT: ${WWOW_VMANGOS_DB_PORT:-3306}
      WWOW_VMANGOS_DB_USER: ${WWOW_VMANGOS_DB_ROOT_USER:-root}
      WWOW_VMANGOS_DB_PASSWORD: ${WWOW_VMANGOS_DB_ROOT_PASSWORD:-root}
      WWOW_VMANGOS_WORLD_PORT: ${WWOW_VMANGOS_WORLD_PORT:-8085}
      WWOW_VMANGOS_SOAP_PORT: ${WWOW_VMANGOS_SOAP_PORT:-7878}
    networks:
      - gameserver-net
    ports:
      - "${WWOW_VMANGOS_WORLD_PUBLISHED_PORT:-8085}:8085"
      - "${WWOW_VMANGOS_SOAP_PUBLISHED_PORT:-7878}:7878"
    volumes:
      - ${WWOW_VMANGOS_SERVER_CONFIG_DIR:-D:/vmangos-server}/mangosd.conf:/wwow-input/mangosd.conf:ro
      - ${WWOW_VMANGOS_DATA_DIR:-D:/MaNGOS/data}:/opt/vmangos/storage/data:ro
      - ./docker/linux/vmangos:/wwow-docker:ro
      - ./docker/linux/vmangos/storage/mangosd/logs:/opt/vmangos/storage/logs
      - ./docker/linux/vmangos/storage/mangosd/honor:/opt/vmangos/storage/honor

networks:
  gameserver-net:
    external: true
