services:
  mangoszero:
    build: .
    container_name: mangoszero-server
    restart: no
    ports:
      - "3724:3724"
      - "8085:8085"
      - "3443:3443"
    volumes:
      - ./game-data:/game-data
    environment:
      - WAN_IP_ADDRESS=127.0.0.1
      - DOCKER_HOST_IP=192.168.10.96
      - MYSQL_ROOT_PASSWORD=mangos
    stdin_open: true
    tty: true

  database:
    image: mysql:5.7
    container_name: mangoszero-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mangos
      - MYSQL_DATABASE=mangos
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Expose MySQL for external access