// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: scenedata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SceneData {

  /// <summary>Holder for reflection information generated from scenedata.proto</summary>
  public static partial class ScenedataReflection {

    #region Descriptor
    /// <summary>File descriptor for scenedata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScenedataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9zY2VuZWRhdGEucHJvdG8SCXNjZW5lZGF0YSJeChBTY2VuZUdyaWRSZXF1",
            "ZXN0Eg4KBm1hcF9pZBgBIAEoDRINCgVtaW5feBgCIAEoAhINCgVtaW5feRgD",
            "IAEoAhINCgVtYXhfeBgEIAEoAhINCgVtYXhfeRgFIAEoAiLdAQoRU2NlbmVH",
            "cmlkUmVzcG9uc2USDgoGbWFwX2lkGAEgASgNEg0KBW1pbl94GAIgASgCEg0K",
            "BW1pbl95GAMgASgCEg0KBW1heF94GAQgASgCEg0KBW1heF95GAUgASgCEhUK",
            "DXRyaWFuZ2xlX2RhdGEYBiADKAISEAoId2Fsa2FibGUYByADKAgSEwoLbm9y",
            "bWFsX2RhdGEYCCADKAISFgoOdHJpYW5nbGVfY291bnQYCSABKA0SDwoHc3Vj",
            "Y2VzcxgKIAEoCBIVCg1lcnJvcl9tZXNzYWdlGAsgASgJIl8KEUxpcXVpZEdy",
            "aWRSZXF1ZXN0Eg4KBm1hcF9pZBgBIAEoDRINCgVtaW5feBgCIAEoAhINCgVt",
            "aW5feRgDIAEoAhINCgVtYXhfeBgEIAEoAhINCgVtYXhfeRgFIAEoAiKXAQoS",
            "TGlxdWlkR3JpZFJlc3BvbnNlEg4KBm1hcF9pZBgBIAEoDRIVCg1saXF1aWRf",
            "bGV2ZWxzGAIgAygCEhQKDGxpcXVpZF90eXBlcxgDIAMoDRIRCgljZWxsX3Np",
            "emUYBCABKAISDwoHY2VsbHNfeBgFIAEoDRIPCgdjZWxsc195GAYgASgNEg8K",
            "B3N1Y2Nlc3MYByABKAhCDKoCCVNjZW5lRGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SceneData.SceneGridRequest), global::SceneData.SceneGridRequest.Parser, new[]{ "MapId", "MinX", "MinY", "MaxX", "MaxY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SceneData.SceneGridResponse), global::SceneData.SceneGridResponse.Parser, new[]{ "MapId", "MinX", "MinY", "MaxX", "MaxY", "TriangleData", "Walkable", "NormalData", "TriangleCount", "Success", "ErrorMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SceneData.LiquidGridRequest), global::SceneData.LiquidGridRequest.Parser, new[]{ "MapId", "MinX", "MinY", "MaxX", "MaxY" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SceneData.LiquidGridResponse), global::SceneData.LiquidGridResponse.Parser, new[]{ "MapId", "LiquidLevels", "LiquidTypes", "CellSize", "CellsX", "CellsY", "Success" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request scene collision data for a bounded region of a map.
  /// The service extracts triangles from VMAP + ADT within the specified bounds.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SceneGridRequest : pb::IMessage<SceneGridRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneGridRequest> _parser = new pb::MessageParser<SceneGridRequest>(() => new SceneGridRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneGridRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SceneData.ScenedataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridRequest(SceneGridRequest other) : this() {
      mapId_ = other.mapId_;
      minX_ = other.minX_;
      minY_ = other.minY_;
      maxX_ = other.maxX_;
      maxY_ = other.maxY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridRequest Clone() {
      return new SceneGridRequest(this);
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 1;
    private uint mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "min_x" field.</summary>
    public const int MinXFieldNumber = 2;
    private float minX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinX {
      get { return minX_; }
      set {
        minX_ = value;
      }
    }

    /// <summary>Field number for the "min_y" field.</summary>
    public const int MinYFieldNumber = 3;
    private float minY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinY {
      get { return minY_; }
      set {
        minY_ = value;
      }
    }

    /// <summary>Field number for the "max_x" field.</summary>
    public const int MaxXFieldNumber = 4;
    private float maxX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxX {
      get { return maxX_; }
      set {
        maxX_ = value;
      }
    }

    /// <summary>Field number for the "max_y" field.</summary>
    public const int MaxYFieldNumber = 5;
    private float maxY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxY {
      get { return maxY_; }
      set {
        maxY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneGridRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneGridRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinX, other.MinX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinY, other.MinY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxX, other.MaxX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxY, other.MaxY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (MinX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinX);
      if (MinY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinY);
      if (MaxX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxX);
      if (MaxY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      if (MinX != 0F) {
        size += 1 + 4;
      }
      if (MinY != 0F) {
        size += 1 + 4;
      }
      if (MaxX != 0F) {
        size += 1 + 4;
      }
      if (MaxY != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneGridRequest other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.MinX != 0F) {
        MinX = other.MinX;
      }
      if (other.MinY != 0F) {
        MinY = other.MinY;
      }
      if (other.MaxX != 0F) {
        MaxX = other.MaxX;
      }
      if (other.MaxY != 0F) {
        MaxY = other.MaxY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Response containing collision triangles for the requested region.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SceneGridResponse : pb::IMessage<SceneGridResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneGridResponse> _parser = new pb::MessageParser<SceneGridResponse>(() => new SceneGridResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneGridResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SceneData.ScenedataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridResponse(SceneGridResponse other) : this() {
      mapId_ = other.mapId_;
      minX_ = other.minX_;
      minY_ = other.minY_;
      maxX_ = other.maxX_;
      maxY_ = other.maxY_;
      triangleData_ = other.triangleData_.Clone();
      walkable_ = other.walkable_.Clone();
      normalData_ = other.normalData_.Clone();
      triangleCount_ = other.triangleCount_;
      success_ = other.success_;
      errorMessage_ = other.errorMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneGridResponse Clone() {
      return new SceneGridResponse(this);
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 1;
    private uint mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "min_x" field.</summary>
    public const int MinXFieldNumber = 2;
    private float minX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinX {
      get { return minX_; }
      set {
        minX_ = value;
      }
    }

    /// <summary>Field number for the "min_y" field.</summary>
    public const int MinYFieldNumber = 3;
    private float minY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinY {
      get { return minY_; }
      set {
        minY_ = value;
      }
    }

    /// <summary>Field number for the "max_x" field.</summary>
    public const int MaxXFieldNumber = 4;
    private float maxX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxX {
      get { return maxX_; }
      set {
        maxX_ = value;
      }
    }

    /// <summary>Field number for the "max_y" field.</summary>
    public const int MaxYFieldNumber = 5;
    private float maxY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxY {
      get { return maxY_; }
      set {
        maxY_ = value;
      }
    }

    /// <summary>Field number for the "triangle_data" field.</summary>
    public const int TriangleDataFieldNumber = 6;
    private static readonly pb::FieldCodec<float> _repeated_triangleData_codec
        = pb::FieldCodec.ForFloat(50);
    private readonly pbc::RepeatedField<float> triangleData_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Packed triangle data: 9 floats per triangle (3 vertices × 3 components)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> TriangleData {
      get { return triangleData_; }
    }

    /// <summary>Field number for the "walkable" field.</summary>
    public const int WalkableFieldNumber = 7;
    private static readonly pb::FieldCodec<bool> _repeated_walkable_codec
        = pb::FieldCodec.ForBool(58);
    private readonly pbc::RepeatedField<bool> walkable_ = new pbc::RepeatedField<bool>();
    /// <summary>
    /// Per-triangle walkability flags (1 = walkable, 0 = wall/obstacle)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<bool> Walkable {
      get { return walkable_; }
    }

    /// <summary>Field number for the "normal_data" field.</summary>
    public const int NormalDataFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_normalData_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> normalData_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Per-triangle normal (3 floats per triangle: nx, ny, nz)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> NormalData {
      get { return normalData_; }
    }

    /// <summary>Field number for the "triangle_count" field.</summary>
    public const int TriangleCountFieldNumber = 9;
    private uint triangleCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TriangleCount {
      get { return triangleCount_; }
      set {
        triangleCount_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 10;
    private bool success_;
    /// <summary>
    /// Status
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "error_message" field.</summary>
    public const int ErrorMessageFieldNumber = 11;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneGridResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneGridResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinX, other.MinX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinY, other.MinY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxX, other.MaxX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxY, other.MaxY)) return false;
      if(!triangleData_.Equals(other.triangleData_)) return false;
      if(!walkable_.Equals(other.walkable_)) return false;
      if(!normalData_.Equals(other.normalData_)) return false;
      if (TriangleCount != other.TriangleCount) return false;
      if (Success != other.Success) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (MinX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinX);
      if (MinY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinY);
      if (MaxX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxX);
      if (MaxY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxY);
      hash ^= triangleData_.GetHashCode();
      hash ^= walkable_.GetHashCode();
      hash ^= normalData_.GetHashCode();
      if (TriangleCount != 0) hash ^= TriangleCount.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      triangleData_.WriteTo(output, _repeated_triangleData_codec);
      walkable_.WriteTo(output, _repeated_walkable_codec);
      normalData_.WriteTo(output, _repeated_normalData_codec);
      if (TriangleCount != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TriangleCount);
      }
      if (Success != false) {
        output.WriteRawTag(80);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      triangleData_.WriteTo(ref output, _repeated_triangleData_codec);
      walkable_.WriteTo(ref output, _repeated_walkable_codec);
      normalData_.WriteTo(ref output, _repeated_normalData_codec);
      if (TriangleCount != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(TriangleCount);
      }
      if (Success != false) {
        output.WriteRawTag(80);
        output.WriteBool(Success);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      if (MinX != 0F) {
        size += 1 + 4;
      }
      if (MinY != 0F) {
        size += 1 + 4;
      }
      if (MaxX != 0F) {
        size += 1 + 4;
      }
      if (MaxY != 0F) {
        size += 1 + 4;
      }
      size += triangleData_.CalculateSize(_repeated_triangleData_codec);
      size += walkable_.CalculateSize(_repeated_walkable_codec);
      size += normalData_.CalculateSize(_repeated_normalData_codec);
      if (TriangleCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TriangleCount);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (ErrorMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneGridResponse other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.MinX != 0F) {
        MinX = other.MinX;
      }
      if (other.MinY != 0F) {
        MinY = other.MinY;
      }
      if (other.MaxX != 0F) {
        MaxX = other.MaxX;
      }
      if (other.MaxY != 0F) {
        MaxY = other.MaxY;
      }
      triangleData_.Add(other.triangleData_);
      walkable_.Add(other.walkable_);
      normalData_.Add(other.normalData_);
      if (other.TriangleCount != 0) {
        TriangleCount = other.TriangleCount;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
          case 50:
          case 53: {
            triangleData_.AddEntriesFrom(input, _repeated_triangleData_codec);
            break;
          }
          case 58:
          case 56: {
            walkable_.AddEntriesFrom(input, _repeated_walkable_codec);
            break;
          }
          case 66:
          case 69: {
            normalData_.AddEntriesFrom(input, _repeated_normalData_codec);
            break;
          }
          case 72: {
            TriangleCount = input.ReadUInt32();
            break;
          }
          case 80: {
            Success = input.ReadBool();
            break;
          }
          case 90: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
          case 50:
          case 53: {
            triangleData_.AddEntriesFrom(ref input, _repeated_triangleData_codec);
            break;
          }
          case 58:
          case 56: {
            walkable_.AddEntriesFrom(ref input, _repeated_walkable_codec);
            break;
          }
          case 66:
          case 69: {
            normalData_.AddEntriesFrom(ref input, _repeated_normalData_codec);
            break;
          }
          case 72: {
            TriangleCount = input.ReadUInt32();
            break;
          }
          case 80: {
            Success = input.ReadBool();
            break;
          }
          case 90: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Liquid data for a region
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LiquidGridRequest : pb::IMessage<LiquidGridRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LiquidGridRequest> _parser = new pb::MessageParser<LiquidGridRequest>(() => new LiquidGridRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LiquidGridRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SceneData.ScenedataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridRequest(LiquidGridRequest other) : this() {
      mapId_ = other.mapId_;
      minX_ = other.minX_;
      minY_ = other.minY_;
      maxX_ = other.maxX_;
      maxY_ = other.maxY_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridRequest Clone() {
      return new LiquidGridRequest(this);
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 1;
    private uint mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "min_x" field.</summary>
    public const int MinXFieldNumber = 2;
    private float minX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinX {
      get { return minX_; }
      set {
        minX_ = value;
      }
    }

    /// <summary>Field number for the "min_y" field.</summary>
    public const int MinYFieldNumber = 3;
    private float minY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinY {
      get { return minY_; }
      set {
        minY_ = value;
      }
    }

    /// <summary>Field number for the "max_x" field.</summary>
    public const int MaxXFieldNumber = 4;
    private float maxX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxX {
      get { return maxX_; }
      set {
        maxX_ = value;
      }
    }

    /// <summary>Field number for the "max_y" field.</summary>
    public const int MaxYFieldNumber = 5;
    private float maxY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MaxY {
      get { return maxY_; }
      set {
        maxY_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LiquidGridRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LiquidGridRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinX, other.MinX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinY, other.MinY)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxX, other.MaxX)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MaxY, other.MaxY)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (MinX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinX);
      if (MinY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinY);
      if (MaxX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxX);
      if (MaxY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MaxY);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      if (MinX != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MinX);
      }
      if (MinY != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(MinY);
      }
      if (MaxX != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(MaxX);
      }
      if (MaxY != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(MaxY);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      if (MinX != 0F) {
        size += 1 + 4;
      }
      if (MinY != 0F) {
        size += 1 + 4;
      }
      if (MaxX != 0F) {
        size += 1 + 4;
      }
      if (MaxY != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LiquidGridRequest other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.MinX != 0F) {
        MinX = other.MinX;
      }
      if (other.MinY != 0F) {
        MinY = other.MinY;
      }
      if (other.MaxX != 0F) {
        MaxX = other.MaxX;
      }
      if (other.MaxY != 0F) {
        MaxY = other.MaxY;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 21: {
            MinX = input.ReadFloat();
            break;
          }
          case 29: {
            MinY = input.ReadFloat();
            break;
          }
          case 37: {
            MaxX = input.ReadFloat();
            break;
          }
          case 45: {
            MaxY = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LiquidGridResponse : pb::IMessage<LiquidGridResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LiquidGridResponse> _parser = new pb::MessageParser<LiquidGridResponse>(() => new LiquidGridResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LiquidGridResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SceneData.ScenedataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridResponse(LiquidGridResponse other) : this() {
      mapId_ = other.mapId_;
      liquidLevels_ = other.liquidLevels_.Clone();
      liquidTypes_ = other.liquidTypes_.Clone();
      cellSize_ = other.cellSize_;
      cellsX_ = other.cellsX_;
      cellsY_ = other.cellsY_;
      success_ = other.success_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LiquidGridResponse Clone() {
      return new LiquidGridResponse(this);
    }

    /// <summary>Field number for the "map_id" field.</summary>
    public const int MapIdFieldNumber = 1;
    private uint mapId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "liquid_levels" field.</summary>
    public const int LiquidLevelsFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_liquidLevels_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> liquidLevels_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Packed liquid cell data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> LiquidLevels {
      get { return liquidLevels_; }
    }

    /// <summary>Field number for the "liquid_types" field.</summary>
    public const int LiquidTypesFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_liquidTypes_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> liquidTypes_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// type per cell
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> LiquidTypes {
      get { return liquidTypes_; }
    }

    /// <summary>Field number for the "cell_size" field.</summary>
    public const int CellSizeFieldNumber = 4;
    private float cellSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CellSize {
      get { return cellSize_; }
      set {
        cellSize_ = value;
      }
    }

    /// <summary>Field number for the "cells_x" field.</summary>
    public const int CellsXFieldNumber = 5;
    private uint cellsX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CellsX {
      get { return cellsX_; }
      set {
        cellsX_ = value;
      }
    }

    /// <summary>Field number for the "cells_y" field.</summary>
    public const int CellsYFieldNumber = 6;
    private uint cellsY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CellsY {
      get { return cellsY_; }
      set {
        cellsY_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 7;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LiquidGridResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LiquidGridResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MapId != other.MapId) return false;
      if(!liquidLevels_.Equals(other.liquidLevels_)) return false;
      if(!liquidTypes_.Equals(other.liquidTypes_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CellSize, other.CellSize)) return false;
      if (CellsX != other.CellsX) return false;
      if (CellsY != other.CellsY) return false;
      if (Success != other.Success) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MapId != 0) hash ^= MapId.GetHashCode();
      hash ^= liquidLevels_.GetHashCode();
      hash ^= liquidTypes_.GetHashCode();
      if (CellSize != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CellSize);
      if (CellsX != 0) hash ^= CellsX.GetHashCode();
      if (CellsY != 0) hash ^= CellsY.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      liquidLevels_.WriteTo(output, _repeated_liquidLevels_codec);
      liquidTypes_.WriteTo(output, _repeated_liquidTypes_codec);
      if (CellSize != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(CellSize);
      }
      if (CellsX != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CellsX);
      }
      if (CellsY != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CellsY);
      }
      if (Success != false) {
        output.WriteRawTag(56);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MapId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MapId);
      }
      liquidLevels_.WriteTo(ref output, _repeated_liquidLevels_codec);
      liquidTypes_.WriteTo(ref output, _repeated_liquidTypes_codec);
      if (CellSize != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(CellSize);
      }
      if (CellsX != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CellsX);
      }
      if (CellsY != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CellsY);
      }
      if (Success != false) {
        output.WriteRawTag(56);
        output.WriteBool(Success);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapId);
      }
      size += liquidLevels_.CalculateSize(_repeated_liquidLevels_codec);
      size += liquidTypes_.CalculateSize(_repeated_liquidTypes_codec);
      if (CellSize != 0F) {
        size += 1 + 4;
      }
      if (CellsX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CellsX);
      }
      if (CellsY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CellsY);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LiquidGridResponse other) {
      if (other == null) {
        return;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      liquidLevels_.Add(other.liquidLevels_);
      liquidTypes_.Add(other.liquidTypes_);
      if (other.CellSize != 0F) {
        CellSize = other.CellSize;
      }
      if (other.CellsX != 0) {
        CellsX = other.CellsX;
      }
      if (other.CellsY != 0) {
        CellsY = other.CellsY;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 18:
          case 21: {
            liquidLevels_.AddEntriesFrom(input, _repeated_liquidLevels_codec);
            break;
          }
          case 26:
          case 24: {
            liquidTypes_.AddEntriesFrom(input, _repeated_liquidTypes_codec);
            break;
          }
          case 37: {
            CellSize = input.ReadFloat();
            break;
          }
          case 40: {
            CellsX = input.ReadUInt32();
            break;
          }
          case 48: {
            CellsY = input.ReadUInt32();
            break;
          }
          case 56: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MapId = input.ReadUInt32();
            break;
          }
          case 18:
          case 21: {
            liquidLevels_.AddEntriesFrom(ref input, _repeated_liquidLevels_codec);
            break;
          }
          case 26:
          case 24: {
            liquidTypes_.AddEntriesFrom(ref input, _repeated_liquidTypes_codec);
            break;
          }
          case 37: {
            CellSize = input.ReadFloat();
            break;
          }
          case 40: {
            CellsX = input.ReadUInt32();
            break;
          }
          case 48: {
            CellsY = input.ReadUInt32();
            break;
          }
          case 56: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
